### PR TITLE
Multidb - sqlite support

### LINKED ISSUE #185: Updating the database client
Would it be possible to update the database client so we can use MySQL 8? Currently, it does not work due to unsupported authentication mode.

### LINKED ISSUE #200: No-config databases or json data storage
FWIW, it would be nice to remove the need for database configuration, or an extra database, by using redis, couchbase, mongodb or other nosql databases, or better yet just store/persist the data in a json file that can be stored on a volume or NFS share.  Configs will not change often enough to justify a full database with its added complexity and overhead.

### PR DESCRIPTION
**Pull request by tg44**
I recreated this PR; https://github.com/jc21/nginx-proxy-manager/pull/256

Separated commits;
 - The first solves the ~~transaction in transaction~~ connection in connection problem in the migration, which causes problems on db-engines which has no multithread support (like sqlite3), also adds a minor refactor to the setup.js
 - The second adds a helper to the 'NOW()' sql function, bcs some db engines (like sqlite) has another syntax for this...
 - The third adds a new db-config option (`knex-native`) and let an experienced knex user to add some own knex-native configurations. Also, this commit showcases an sqlite3 config, and adds psql and sqlite3 libs.

Probably fixes #185 and fixes #200

Missing things;
 - document the sqlite config
 - try out the psql support

### CODE REVIEW

**Comment by tg44** [comment]
I think it is a CI error and not an error with the code...

File: backend/setup.js [hunk 1]
```diff
@@ -5,111 +5,145 @@ const logger              = require('./logger').setup;
...
-				logger.debug('Admin user setup not required');
+			} if (debug_mode) {
+				logger.debug('Default setting setup not required');
 			}
 		});
+}
+
+module.exports = function () {
+	return new Promise((resolve, reject) => {
+		return setupJwt(resolve, reject);
```
Comment (jc21) [inline backend/setup.js:143]: setupJwt is not a promise, so returning it as is will be async but won't reject on error properly. If it were a promise, you wouldn't need to wrap it in a Promise constructor either.

File: backend/setup.js [hunk 2]
```diff
@@ -5,111 +5,145 @@ const logger              = require('./logger').setup;
...
+					logger.info('Initial admin setup completed');
+				});
+		} else if (debug_mode) {
+			logger.debug('Admin user setup not required');
+		}
+	});
+}
 
-				return userModel
+function setupDefaultSettings() {
```
Comment (jc21) [inline backend/setup.js:117]: Not quite sure why you took this from a Migration and put it here, you're not doing that to any other migrations...

**Comment by jc21** [comment]
Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-510`

File: backend/setup.js (hunk 2 above)
Comment (tg44) [reply backend/setup.js:117]: This is the only migration where the concept was broken. I didn't needed to do it in any other migration bcs all of the other migrations just modify the schemas, and not trying to insert things to it. (BTW; we insert users in the setup but we insert settings in a migration?)

As I understand when you run the migrations it connects to the db. And when you run the `settingModel.query().insert()`  it tries to connect to the db again (while we still migrate). Which in multithreaded env (like pg or mysql) not a big deal, you can have multiple connections/connection pools to the same db. But in sqlite you hava a lock on the file, so while one connection is attached to the db, the other connection "can't" connect to it.

If you are interested in it deeper I referenced an issue in the commit message.

File: backend/setup.js (hunk 1 above)
Comment (tg44) [reply backend/setup.js:143]: I literally just extracted the code to a new function. I think if it has some logical error now, it had it in the past too.

Probably I could have moved the promise creation to the `setupJwt` too, but probably it is just a matter of taste.

Comment (tg44) [reply backend/setup.js:143]: ohhh, or I just simply not need to write the "return" keyword in this case?

**Comment by tg44** [comment]
Starting from today I use this image on my home server.

File: backend/setup.js (hunk 1 above)
Comment (jc21) [reply backend/setup.js:143]: Not really, it just could be written differently but let's just get it through for now

File: backend/setup.js (hunk 2 above)
Comment (jc21) [reply backend/setup.js:117]: Ah ok I get your point about breaking the concept. All good.

To clarify, "migrations" should be changes that occur before the App really runs. It's used on the Knex layer and should not perform any logic on data and assumes the database is in a certain state prior to execution.

Setup users is part of the app because it has to check if there is an admin user and only when not found, it creates one. As this happens on startup each time, a migration is not the right place for that.

Comment (tg44) [reply backend/setup.js:117]: I understand this, BUT if injecting users is a runtime check, inserting settings why not? Also if inserting settings is essential to start the app, I think the default user is essential to start the app too. It breaks the logic if one or the other handled differently. I think it's mostly a theoretical question if inserting default data is part of the db migration or not, and most of the JVM world would place them to the migrations (including myself), but here the code already introduced both ways, and I simply chose the comfy side.

**Comment by tg44** [comment]
Thanks the merge!
